// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS. '
          'Reconfigure using the FlutterFire CLI.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Windows. '
          'Reconfigure using the FlutterFire CLI.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux. '
          'Reconfigure using the FlutterFire CLI.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQd6sadD37i7h4I_Axq8C24dSlfrtRtfQ',
    appId: '1:822979000344:web:70391038aaa77b441f2b6d',
    messagingSenderId: '822979000344',
    projectId: 'ecobreack-5dfe5',
    authDomain: 'ecobreack-5dfe5.firebaseapp.com',
    storageBucket: 'ecobreack-5dfe5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd8c4z93--NVeTTAdLzRvkimm3tOgoMpI',
    appId: '1:822979000344:android:b373a9f56f1775e61f2b6d',
    messagingSenderId: '822979000344',
    projectId: 'ecobreack-5dfe5',
    storageBucket: 'ecobreack-5dfe5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfkb6jcdgzA05c8YSSFd5kROqHbVEKVjA',
    appId: '1:822979000344:ios:6f7b1a89ee017ad41f2b6d',
    messagingSenderId: '822979000344',
    projectId: 'ecobreack-5dfe5',
    storageBucket: 'ecobreack-5dfe5.appspot.com',
    iosBundleId: 'com.emasEco.Ecobreak',
  );
}
